services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: swift_shuttle_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root  # Same as the MySQL root password
    depends_on:
      - db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: swift_shuttle_db
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DJANGO_SETTINGS_MODULE: swift_shuttle.settings  # Add this line

volumes:
  db_data:
  media_data:
